spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

server.port=${PORT:8081}

spring.application.name=payment-validation-service
validator.rule.name=Duplicate_Txn_Validator,Fraud_Check_Validator

# Fraud detection
fraud.velocity.max-txn-per-hour=5
fraud.threshold.medium=30
fraud.threshold.high=70

# AI Configuration
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.1-8b-instant